// Code generated by protoc-gen-go.
// source: platform.proto
// DO NOT EDIT!

/*
Package platform is a generated protocol buffer package.

It is generated from these files:
	platform.proto

It has these top-level messages:
	Request
	RoutedMessage
	ConsumeEvent
	Documentation
	DocumentationList
	Error
	Event
	RouterConfig
	PossibleError
*/
package platform

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Method int32

const (
	Method_REPLY Method = 14
	Method_GET   Method = 15
)

var Method_name = map[int32]string{
	14: "REPLY",
	15: "GET",
}
var Method_value = map[string]int32{
	"REPLY": 14,
	"GET":   15,
}

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}
func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (x *Method) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Method_value, data, "Method")
	if err != nil {
		return err
	}
	*x = Method(value)
	return nil
}

type Resource int32

const (
	Resource_DOCUMENTATION      Resource = 65533
	Resource_DOCUMENTATION_LIST Resource = 65534
	Resource_ERROR              Resource = 65535
)

var Resource_name = map[int32]string{
	65533: "DOCUMENTATION",
	65534: "DOCUMENTATION_LIST",
	65535: "ERROR",
}
var Resource_value = map[string]int32{
	"DOCUMENTATION":      65533,
	"DOCUMENTATION_LIST": 65534,
	"ERROR":              65535,
}

func (x Resource) Enum() *Resource {
	p := new(Resource)
	*p = x
	return p
}
func (x Resource) String() string {
	return proto.EnumName(Resource_name, int32(x))
}
func (x *Resource) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Resource_value, data, "Resource")
	if err != nil {
		return err
	}
	*x = Resource(value)
	return nil
}

type Request struct {
	Body             []byte  `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Resource         *int32  `protobuf:"varint,2,opt,name=resource" json:"resource,omitempty"`
	Method           *int32  `protobuf:"varint,3,opt,name=method" json:"method,omitempty"`
	IpAddress        *string `protobuf:"bytes,4,opt,name=ip_address" json:"ip_address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetResource() int32 {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return 0
}

func (m *Request) GetMethod() int32 {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return 0
}

func (m *Request) GetIpAddress() string {
	if m != nil && m.IpAddress != nil {
		return *m.IpAddress
	}
	return ""
}

type RoutedMessage struct {
	Id               *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Method           *int32  `protobuf:"varint,2,opt,name=method" json:"method,omitempty"`
	Resource         *int32  `protobuf:"varint,3,opt,name=resource" json:"resource,omitempty"`
	ReplyTopic       *string `protobuf:"bytes,4,opt,name=reply_topic" json:"reply_topic,omitempty"`
	Body             []byte  `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoutedMessage) Reset()         { *m = RoutedMessage{} }
func (m *RoutedMessage) String() string { return proto.CompactTextString(m) }
func (*RoutedMessage) ProtoMessage()    {}

func (m *RoutedMessage) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *RoutedMessage) GetMethod() int32 {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return 0
}

func (m *RoutedMessage) GetResource() int32 {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return 0
}

func (m *RoutedMessage) GetReplyTopic() string {
	if m != nil && m.ReplyTopic != nil {
		return *m.ReplyTopic
	}
	return ""
}

func (m *RoutedMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ConsumeEvent struct {
	Description      *string          `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Event            *Event           `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
	Responses        []*Event         `protobuf:"bytes,3,rep,name=responses" json:"responses,omitempty"`
	PossibleErrors   []*PossibleError `protobuf:"bytes,4,rep,name=possible_errors" json:"possible_errors,omitempty"`
	IsDeprecated     *bool            `protobuf:"varint,5,opt,name=is_deprecated" json:"is_deprecated,omitempty"`
	Version          *string          `protobuf:"bytes,6,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ConsumeEvent) Reset()         { *m = ConsumeEvent{} }
func (m *ConsumeEvent) String() string { return proto.CompactTextString(m) }
func (*ConsumeEvent) ProtoMessage()    {}

func (m *ConsumeEvent) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *ConsumeEvent) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ConsumeEvent) GetResponses() []*Event {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *ConsumeEvent) GetPossibleErrors() []*PossibleError {
	if m != nil {
		return m.PossibleErrors
	}
	return nil
}

func (m *ConsumeEvent) GetIsDeprecated() bool {
	if m != nil && m.IsDeprecated != nil {
		return *m.IsDeprecated
	}
	return false
}

func (m *ConsumeEvent) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type Documentation struct {
	Description      *string         `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	ConsumeEvents    []*ConsumeEvent `protobuf:"bytes,2,rep,name=consume_events" json:"consume_events,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Documentation) Reset()         { *m = Documentation{} }
func (m *Documentation) String() string { return proto.CompactTextString(m) }
func (*Documentation) ProtoMessage()    {}

func (m *Documentation) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Documentation) GetConsumeEvents() []*ConsumeEvent {
	if m != nil {
		return m.ConsumeEvents
	}
	return nil
}

type DocumentationList struct {
	Documentations   []*Documentation `protobuf:"bytes,1,rep,name=documentations" json:"documentations,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *DocumentationList) Reset()         { *m = DocumentationList{} }
func (m *DocumentationList) String() string { return proto.CompactTextString(m) }
func (*DocumentationList) ProtoMessage()    {}

func (m *DocumentationList) GetDocumentations() []*Documentation {
	if m != nil {
		return m.Documentations
	}
	return nil
}

type Error struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type Event struct {
	Organization     *string `protobuf:"bytes,4,opt,name=organization" json:"organization,omitempty"`
	Method           *string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Resource         *string `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	Payload          *string `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetOrganization() string {
	if m != nil && m.Organization != nil {
		return *m.Organization
	}
	return ""
}

func (m *Event) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Event) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

func (m *Event) GetPayload() string {
	if m != nil && m.Payload != nil {
		return *m.Payload
	}
	return ""
}

type RouterConfig struct {
	Protocol         *string `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	Host             *string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port             *string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RouterConfig) Reset()         { *m = RouterConfig{} }
func (m *RouterConfig) String() string { return proto.CompactTextString(m) }
func (*RouterConfig) ProtoMessage()    {}

func (m *RouterConfig) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *RouterConfig) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *RouterConfig) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

type PossibleError struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PossibleError) Reset()         { *m = PossibleError{} }
func (m *PossibleError) String() string { return proto.CompactTextString(m) }
func (*PossibleError) ProtoMessage()    {}

func (m *PossibleError) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *PossibleError) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("platform.Method", Method_name, Method_value)
	proto.RegisterEnum("platform.Resource", Resource_name, Resource_value)
}
